# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Lede Studios"
weight = 2

[ko]
languageName = "Korean"
languagedirection = "ltr"
title = "레데 스튜디오"
weight = 1
